language: ko-KR

tone_instructions: >
  당신은 숙련된 풀스택 개발자입니다. 목표는 코드의 품질을 높이고
  클린 코드, 확장성, 성능, 안정성 측면에서 개선 방향을 제시하는 것입니다.
  1. 리뷰는 간결하지만 구체적으로 작성합니다.
  2. 코드의 의도, 구조, 유지보수성, 테스트 가능성을 중심으로 평가합니다.
  3. 비판보다 해결책 중심으로 제안합니다.
  4. 필요 시 예시 코드나 레퍼런스를 함께 제공합니다.

reviews:
  profile: chill
  high_level_summary: true
  changed_files_summary: false
  sequence_diagrams: false
  request_changes_workflow: false
  assess_linked_issues: true
  related_issues: false
  related_prs: false
  suggested_labels: false
  auto_apply_labels: false
  suggested_reviewers: false
  auto_assign_reviewers: false
  poem: false
  auto_review_enabled: true
  incremental_review_enabled: true
  review_status: true

  path_instructions:
    - path: src/app/**
      instructions: |
        1. 서버와 클라이언트 컴포넌트의 구분이 올바른지 확인해주세요.
        2. 페이지 구조, 데이터 fetch, API 라우팅이 효율적인지 검토해주세요.
        3. 불필요한 리렌더링, 에러 핸들링 누락이 없는지 확인해주세요.
        4. SEO 설정(title, description 등)이 적절히 포함되어 있는지 점검해주세요.

    - path: src/components/**
      instructions: |
        1. 컴포넌트가 단일 책임 원칙에 맞게 분리되어 있는지 확인해주세요.
        2. props 타입 정의가 명확하고 재사용성을 고려했는지 검토해주세요.
        3. UI 접근성(ARIA 등)과 스타일 일관성을 확인해주세요.

chat:
  auto_reply: true

knowledge_base:
  web_search:
    enabled: true
  code_guidelines:
    enabled: true
    filePatterns:
      - docs/code-convention.md
  learnings:
    scope: local
  issues:
    scope: local
  pull_requests:
    scope: local